travelru/my_travel/urls.py
# pylint: disable=invalid-name

from django.urls import path

from my_travel.views import my_travel, delete_hotel_from_travel, delete_avia_from_travel

app_name = "my_travel"

urlpatterns = [
    path("", my_travel, name="my_travel"),
    path("delete_hotel/", delete_hotel_from_travel, name="delete_hotel_from_travel"),
    path("delete_avia/", delete_avia_from_travel, name="delete_avia_from_travel"),
]

travelru/travelru/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("my-travel/", include("my_travel.urls", namespace="my_travel")),
    path("", include("waysearch.urls", namespace="waysearch")),
    path('search_hotels/', include('search_hotels.urls', namespace='search_hotels')),  # noqa: E501

]

travelru/my_travel/models.py
from django.db import models
from django.conf import settings

# Create your models here.
# class User(models):
#     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Item(models.Model):
    ITEM_TYPE = [
        ('HOTEL', 'Hotel'),
        ('AVIA', 'Avia')
        ]
#    id = models.AutoField()
    name = models.CharField(max_length=40)
    city_from = models.CharField(max_length=40)
    city_to = models.CharField(max_length=40)
    item_type = models.CharField(max_length=10, choices=ITEM_TYPE)
    date_beg = models.DateField()
    time_beg = models.TimeField()
    date_end = models.DateField()
    time_end = models.TimeField()
    price = models.IntegerField()
    hotel_city = models.CharField(max_length=30, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#    user


class Avia(models.Model):
    item = models.OneToOneField(Item, on_delete=models.CASCADE, null=True)
    airline = models.CharField(max_length=30, null=True)
    departure_at = models.DateTimeField(null=True)
    return_at = models.DateTimeField(null=True)
    city_from = models.CharField(max_length=40, null=True)
    city_to = models.CharField(max_length=40, null=True)
    price = models.IntegerField(null=True)
    link = models.CharField(max_length=300)


class Hotel(models.Model):
    ITEM_TYPE = [
        ('HOTEL', 'Hotel'),
        ]
    name = models.CharField(max_length=40, null=True)
    item_type = models.CharField(max_length=10, choices=ITEM_TYPE, null=True)
    item = models.OneToOneField(Item, on_delete=models.CASCADE, null=True)
    nights = models.IntegerField(null=True)
    price = models.IntegerField(null=True)
    total_cost = models.IntegerField(null=True)
    hotel_city = models.CharField(max_length=30, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

travelru/my_travel/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

from my_travel.models import Item, Hotel, Avia


# Create your views here.

def my_travel(request):
    my_travel_list = Item.objects.all().order_by('date_beg', 'time_beg')
    my_avia_list = Avia.objects.all()
    my_hotels_list = Hotel.objects.all()
    return render(request, 'my_travel.html', {'my_travel_list': my_travel_list,
                                              'my_hotels_list': my_hotels_list,
                                              'my_avia_list': my_avia_list,
                                              })


def delete_hotel_from_travel(request):
    print(request.POST)
    id = request.POST['hotel_id']
    hotel = Hotel.objects.get(id=id)
    print('hotel', hotel)
    hotel.delete()
    return HttpResponseRedirect('/my-travel')


def delete_avia_from_travel(request):
    id = request.POST['avia_id']
    avia = Avia.objects.get(id=id)
    print('avia', avia)
    avia.delete()
    return HttpResponseRedirect('/my-travel')

travelru/my_travel/templates/my_travel.html
{% extends "base.html" %}
{% load i18n %}
{% load waysearch_tag %}

{% block page_title %}
    Мое путешествие:
{% endblock %}


{% block main_container %}
    <div class="container-md py-2">
        <div><h3 class="text-center" style="
                 margin-bottom: 40px;">Моё путешествие на Create-travel.ru</h3></div>
        {% if not my_hotels_list and not my_avia_list %}
            <p class="text-center">Здесь пока нет путешествия :(</p>
        {% endif %}
        <ul>

            {% for hotel in my_hotels_list %}
                <div class="card">
                    <div class="card-body">
                        <h3>{{ hotel.hotel_city }}. Проживание </h3>
                        <p>{{ hotel.name }}</p>
                        <p>Пользователь: {{ hotel.user }}</p>
                        <ul class="list-inline">
                            <li class="list-inline-item">Цена за сутки: {{ hotel.price }} ₽</li>
                            <li class="list-inline-item">Количество ночей: {{ hotel.nights }}</li>
                            <li class="list-inline-item ">
                                <strong>Стоимость: {{ hotel.total_cost }} ₽</strong>
                            </li>
                            <ul class="list-inline">
                                <form method="post" action="{% url 'my_travel:delete_hotel_from_travel' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="hotel_id" value="{{ hotel.id }}"/>
                                    <button type="submit" class="btn btn-warning" style="margin-top: 20px;">
                                        Удалить из путешествия
                                    </button>
                                </form>
                            </ul>
                        </ul>
                    </div>
                </div>
            {% endfor %}

            {% for avia in my_avia_list %}
                <div class="card">
                <div class="card-body">
                    <h3>{{ avia.city_from }}. Авиабилеты </h3>
                    <p>Авиаперевозчик: {{ avia.airline }}</p>
                    <div class="row">
                        <div class="col">
                            <p>Туда:</p>
                            <ul class="list-inline">
                                <li class="list-inline-item">{{ avia.departure_at }}</li>
                            </ul>
                            <ul class="list-inline">
                                <li class="list-inline-item">Пункт
                                    отправления: {{ avia.city_from }}</li>
                                <li>Пункт
                                    назначения: {{ avia.city_to }}</li>
                            </ul>
                        </div>
                        <div class="col">
                            <p>Обратно:</p>
                            <ul class="list-inline">
                                <li class="list-inline-item">{{ avia.return_at }}</li>
                            </ul>
                            <ul class="list-inline">
                                <li class="list-inline-item">Пункт
                                    отправления: {{ avia.city_to }}</li>
                                <li>Пункт
                                    назначения: {{ avia.city_from }}</li>
                            </ul>
                        </div>
                        <p class="text-center" style="margin-top: 20px; margin-bottom: 0px;">Цена:
                            <strong>{{ avia.price }}</strong> ₽</p>
                        <form method="post" action="{% url 'my_travel:delete_avia_from_travel' %}">
                            {% csrf_token %}
                            <input type="hidden" name="avia_id" value="{{ avia.id }}"/>
                            <button type="submit" class="btn btn-warning">
                                Удалить из путешествия
                            </button>
                        </form>
                    </div>
                </div>
            {% endfor %}




            {#                                    {% elif item.item_type == 'AVIA' %}#}
            {#                                    <div class="card">#}
            {#                                        <div class="card-body">#}
            {#                                            <h3>{{ item.city_from }}. Авиабилеты </h3>#}
            {#                                            <p>{{ item.name }}</p>#}
            {#                                            <p>{{ item.date_beg }} {{ item.time_beg }} - {{ item.date_end }} {{ item.time_end }}</p>#}
            {#                                            <p>Пользователь: {{ item.user }}</p>#}
            {#                                            <p>Цена: {{ item.price }} ₽</p>#}
            {#                                            <form method="post" action="{% url 'my_travel:delete_hotel_from_travel' %}">#}
            {#                                                {% csrf_token %}#}
            {#                                                <input type="hidden" name="id" value="{{ item.id }}"/>#}
            {#                                                <button type="submit" class="btn btn-warning">Удалить</button>#}
            {#                                            </form>#}
            {#                                        </div>#}
            {#                                    </div>#}
            {#                                {% endif %}#}


            </div>
        </ul>
    </div>
{% endblock %}