travelru/search_hotels/urls.py
# pylint: disable=invalid-name

from django.urls import path

from search_hotels.views import search_hotels, add_hotel_to_travel

app_name = "search_hotels"

urlpatterns = [
    path("", search_hotels, name="search_hotels"),
    path("add/", add_hotel_to_travel, name="add_hotel_to_travel"),
#    path("my-travel/", my_travel, name="my_travel"),

]

travelru/travelru/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("my-travel/", include("my_travel.urls", namespace="my_travel")),
    path("", include("waysearch.urls", namespace="waysearch")),
    path('search_hotels/', include('search_hotels.urls', namespace='search_hotels')),  # noqa: E501

]

travelru/waysearch/urls.py
from django.urls import path
from waysearch.views import search_avia_page, search_train_page, index, add_avia_to_travel

app_name = "waysearch"  # pylint: disable=invalid-name

urlpatterns = [
    path("", index, name="index"),
    path("search_avia/", search_avia_page, name="search_avia"),
    path("search_avia/add/", add_avia_to_travel, name="add_avia_to_travel"),
    path("search_train/", search_train_page, name="search_train"),

]

travelru/waysearch/models.py
"""
models
"""
from django.db import models


# Create your models here.
class Country(models.Model):
    db_id = models.PositiveIntegerField(primary_key=True)
    name_rus = models.CharField(max_length=100, blank=False, unique=True)
    name_eng = models.CharField(max_length=100, unique=True, null=True)
    code_eng = models.CharField(max_length=3, null=True)

    def __str__(self):
        return self.name_rus


class City(models.Model):
    country = models.ForeignKey(Country, default=1, on_delete=models.CASCADE)
    id_aviasales = models.PositiveIntegerField(default=0, null=True)
    name_rus = models.CharField(max_length=70, blank=False, unique=True, primary_key=True)
    name_eng = models.CharField(max_length=70, null=True)
    code_eng = models.CharField(max_length=3, null=True)

    def __str__(self):
        return self.name_rus

    @classmethod
    def import_from_file(cls):
        filename = '.\waysearch\IATA_aiports.txt'
        with open(filename, 'r') as f:
            str_lines =f.read().splitlines()
#           print(str_list1[1])
            for line in str_lines:
                words = line.split('\t')
                print(f"length: {cls.objects.filter(name_rus=words[0]).count()}")
                if cls.objects.filter(name_rus=words[0]).count() == 0:
                    print(f"{words[0]} - new city add")
                    new_city = City(name_rus=words[0])
                    new_city.save()
                else:
                    print(f"{words[0]} - city already exists")



class Airport(models.Model):
    city = models.ForeignKey(City, default="Москва", on_delete=models.CASCADE)
    name_rus = models.CharField(max_length=70, blank=False, unique=True)
    name_eng = models.CharField(max_length=70, null=True)
    code_IATA = models.CharField(max_length=3, null=True, unique=True)
    code_ICAO = models.CharField(max_length=4, null=True)
    code_rus = models.CharField(max_length=3, null=True)

    def __str__(self):
        ret_string = f"{self.name_rus}({self.code_IATA}), г.{self.city.name_rus}"
        return ret_string

    @classmethod
    def import_from_file(cls):
        filename = '.\waysearch\IATA_aiports.txt'
        with open(filename, 'r') as f:
            str_lines =f.read().splitlines()
#           print(str_list1[1])
            for line in str_lines:
                words = line.split('\t')
                print(f"city={City.objects.get(name_rus=words[0])}, name_rus={words[1]}, code_IATA={words[2]}, "
                      f"code_ICAO={words[3]},  code_rus={words[4]}")
                if cls.objects.filter(name_rus=words[1]).count() == 0:
                    if not words[2] == " ":
                        print(f"{words[1]} - new airport add")
                        new_airport = Airport(city=City.objects.get(name_rus=words[0]), name_rus=words[1], code_IATA=words[2],
                                              code_ICAO=words[3], code_rus=words[4])
                        new_airport.save()
                    else:
                        print(f"{words[2]} - NO CODE")
                else:
                    print(f"{words[1]} - ERROR! airport already exists")

travelru/waysearch/forms.py
"""
forms
"""
from datetime import datetime

from django import forms


class WaysearchForm(forms.Form):
    """
    Avia tickets search
    """
    today_date = datetime.today().strftime("%Y-%m-%d")
    departure_city = forms.CharField(
        label='Откуда',
        widget=forms.TextInput(
            attrs={
                'class': 'city-auto form-control',
                'placeholder': 'Откуда'}
        )
    )
    arrival_city = forms.CharField(
        label='Куда',
        widget=forms.TextInput(
           attrs={
                'class': 'city-auto form-control',
                'placeholder': 'Куда'}
        )
    )
    departure_date = forms.DateField(
        label='Дата вылета',
        widget=forms.DateInput(
            attrs={
                'type': 'date',
                'class': 'form-control',
                'min': today_date,
                'onkeydown': 'return false'}
        )
    )
    arrival_date = forms.DateField(
        label='Дата обратно',
        widget=forms.DateInput(
            attrs={
                'type': 'date',
                'class': 'form-control',
                'min': today_date,
                'onkeydown': 'return false'}
        )
    )

travelru/waysearch/views.py
"""
views
"""
# flake8: noqa
import requests
from datetime import datetime, timedelta
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate
from waysearch.forms import WaysearchForm
from waysearch.configuration import IATA
from travelru.settings import TOKEN_AVIASALES
from my_travel.models import Item, Avia


def index(request):
    """
    index
    """
    return render(request, "index.html")


def search_avia_page(request):
    """
    search_avia_page
    """
    data_info = {"data": ""}
    search_avia = WaysearchForm()
    if request.method == "POST":
        search_avia = WaysearchForm(request.POST)
        url = 'https://api.travelpayouts.com/aviasales/v3/prices_for_dates'
        headers = {'Content-Type': 'application/json'}
        data = request.POST
        origin = data['departure_city']
        destination = data['arrival_city']

        city_1, city_2 = False, False
        for city_iata in IATA:
            if city_iata['city_name'].lower() in origin.lower():
                city_1 = True
            if city_iata['city_name'].lower() in destination.lower():
                city_2 = True
        if not city_1:
            search_avia.add_error('departure_city', f'Город откуда - {origin} не найден')
        if not city_2:
            search_avia.add_error('arrival_city', f'Город куда - {destination} не найден')
        if not city_1 or not city_2:
            return render(request, 'search_avia.html', {'form': search_avia})

        departure_at = data['departure_date']
        return_at = data['arrival_date']
        if departure_at > return_at:
            search_avia.add_error('departure_date',
                                  'Дата возвращения должна быть позже даты вылета')
            return render(request, 'search_avia.html', {'form': search_avia})
        # direct — получить рейсы без пересадок. По умолчанию false
        params = {'origin': from_city_to_code(origin),
                  'destination': from_city_to_code(destination),
                  'currency': 'rub',
                  'departure_at': departure_at,
                  'return_at': return_at,
                  'sorting': 'price',
                  'direct': 'true',
                  'token': TOKEN_AVIASALES}
        try:
            data_info = requests.get(url, headers=headers, params=params).json()
            # print(data_info)
        except Exception:  # pylint: disable=broad-except
            search_avia.add_error('departure_city', 'Сервис API недоступен.')
            return render(request, 'search_avia.html', {'form': search_avia})
        data_info['data_f'] = data
    data_info["iata"] = IATA

    return render(request, 'search_avia.html', {'form': search_avia, "data": data_info})


def search_train_page(request):
    """
    search_train_page
    """
    return render(request, "search_train.html")


def from_city_to_code(city):
    """
    from_city_to_code
    """
    for iata_tag in IATA:
        if 'москва' in city.lower():
            airport = city.split()[-1].strip("()")
            if iata_tag['name'] == airport:
                return iata_tag['code']
        else:
            if iata_tag['city_name'] == city:
                return iata_tag['code']
    return ""


def add_avia_to_travel(request):
    print(request.POST)
    if not request.user.is_authenticated:
        print('AnonymousUser detected!')
        user = authenticate(username='guest', password='fdsa4321')
    else:
        user = request.user

    airline = request.POST['airline']
    departure_at = datetime.strptime(request.POST['datetime_beg'], "%Y-%m-%dT%H:%M:%S%z")
    return_at = datetime.strptime(request.POST['datetime_end'], "%Y-%m-%dT%H:%M:%S%z")
    city_from = request.POST['city_from']
    city_to = request.POST['city_to']
    price = int(request.POST['price'])

    direct_flight = Avia.objects.create(airline=airline,
                                        price=price,
                                        departure_at=departure_at,
                                        return_at=return_at,
                                        city_from=city_from,
                                        city_to=city_to,
                                        )


    # datetime_beg = datetime.strptime(request.POST['datetime_beg'], "%Y-%m-%dT%H:%M:%S%z")
    # name = f"{city_from} - {city_to}"
    # datetime_beg = datetime.strptime(request.POST['datetime_beg'], "%Y-%m-%dT%H:%M:%S%z")
    # date_beg = datetime_beg.date()
    # time_beg = datetime_beg.time()
    # datetime_end = datetime_beg + timedelta(minutes=int(request.POST['duration']))
    # date_end = datetime_end.date()
    # time_end = datetime_end.time()
    # item1 = Item.objects.create(name=name, item_type="AVIA", price=price/2, user=user,
    #                             date_beg=date_beg, date_end=date_end,
    #                             time_beg=time_beg, time_end=time_end,
    #                             city_from=city_from, city_to=city_to)
    # # Полет обратно
    # if not (datetime_end == ''):
    #     name = f"{city_to} - {city_from}"
    #     datetime_beg = datetime.strptime(request.POST['datetime_end'], "%Y-%m-%dT%H:%M:%S%z")
    #     date_beg = datetime_beg.date()
    #     time_beg = datetime_beg.time()
    #     datetime_end = datetime_beg + timedelta(minutes=int(request.POST['duration']))
    #     date_end = datetime_end.date()
    #     time_end = datetime_end.time()
    #     item2 = Item.objects.create(name=name, item_type="AVIA", price=price/2, user=user,
    #                                 date_beg=date_beg, date_end=date_end,
    #                                 time_beg=time_beg, time_end=time_end,
    #                                 city_from=city_to, city_to=city_from)

    #    avia = Avia.objects.create(item=item, link="testlink")
    return HttpResponseRedirect('/my-travel')

travelru/waysearch/templates/index.html
{% extends 'base.html' %}


{% block page_title %}
    Main page
{% endblock %}


{% block main_container %}
    <div class="container-md py-2">
        <h3>TravelRu</h3>
        <p class="fs-4">Поиск билетов</p>
        <ul>
            <a href="{% url 'waysearch:search_avia' %}">Поиск авиабилетов</a>
        </ul>
        <ul>
            <a href="{% url 'waysearch:search_train' %}">Поиск Ж/Д билетов</a>
        </ul>
        <p class="fs-4">Поиск проживания</p>
        <ul>
            <a href={% url 'search_hotels:search_hotels' %}>Поиск отелей</a>
        </ul>
    </div>
{% endblock %}

travelru/waysearch/templates/search_avia.html
{% extends "base.html" %}
{% load i18n %}
{% load waysearch_tag %}


{% block page_title %}
    Поиск авиамаршрутов
{% endblock %}


{% block main_container %}
    <div class="container-md py-2">
        <div><h3 class="text-center" style="
                 margin-bottom: 40px;">Поиск авиамаршрутов на Create-travel.ru</h3></div>
        {#        <h3 class="pb-3">#}
        {#            Поиск авиамаршрутов#}
        {#        </h3>#}
        <div class="forms-resolver">
            <form method="post" class="row gy-2 gx-3 align-items-center mb-3">
                {% csrf_token %}
                <div class="col-auto">
                    {#                    <div class="row row-cols-4">#}
                    <div class="row row-cols-5">
                        <div class="col">{{ form.departure_city.label }}</div>
                        <div class="col">{{ form.arrival_city.label }}</div>
                        <div class="col">{{ form.departure_date.label }}</div>
                        <div class="col">{{ form.arrival_date.label }}</div>
                        <div class="col"></div>
                        <div class="col">{{ form.departure_city|default:'' }}</div>
                        <div class="col">{{ form.arrival_city }}</div>
                        <div class="col">{{ form.departure_date }}</div>
                        <div class="col">{{ form.arrival_date }}</div>
                        <div class="col">
                            <button type="submit" class="btn btn-primary">{% trans "Найти" %}</button>
                        </div>
                    </div>


                </div>

                {#                <div class="col">#}
                {#                    <button type="submit" class="btn btn-primary">{% trans "Search" %}</button>#}
                {#                </div>#}
                {% for error, descriptions in form.errors.items %}
                    {% for description in descriptions %}
                        <p class="text-danger">{{ description }}</p>
                    {% endfor %}
                    {#                    <div class="text-danger">#}
                    {#                        {{ field.errors }}#}
                    {#                    </div>#}
                    {#                    {{ field.label_tag }}#}
                    {#                    {{ field }}#}
                {% endfor %}
            </form>
            {% if data.data %}
                <div class="container-md py-2">
                    <h3 class="pb-3">
                        {% trans "Найденные билеты:" %}
                    </h3>
                    {% for flight in data.data %}
                        <div class="p-3 mb-4 bg-light rounded-3">
                            <div class="container-md py-2" style="padding-top: 5px; margin-left: 20px;">
                                <p>Авиаперевозчик: {% airline_translated flight.airline %}</p>
                                <div class="row">
                                    <div class="col">
                                        <p>Туда:</p>
                                        <ul class="list-inline">
                                            <li class="list-inline-item">{% formatted_depature flight.departure_at %}</li>
                                        </ul>
                                        <ul class="list-inline">
                                            <li class="list-inline-item">Пункт
                                                отправления: {{ form.departure_city.value }} {{ flight.origin_airport }}</li>
                                            <li >Пункт
                                                назначения: {{ form.arrival_city.value }} {{ flight.destination_airport }}</li>
                                        </ul>
                                    </div>
                                    <div class="col">
                                        <p>Обратно:</p>
                                        <ul class="list-inline">
                                            <li class="list-inline-item">{% formatted_depature flight.return_at %}</li>
                                        </ul>
                                        <ul class="list-inline">
                                            <li class="list-inline-item">Пункт
                                                отправления: {{ form.arrival_city.value }} {{ flight.destination_airport }}</li>
                                            <li>Пункт
                                                назначения: {{ form.departure_city.value }} {{ flight.origin_airport }}</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <p class="text-center">Цена: <strong>{{ flight.price }} ₽</strong>
                            <ul class="list-inline">
                                <form method="post" action="{% url 'waysearch:add_avia_to_travel' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="type" value="Avia"/>
                                    <input type="hidden" name="city_from" value="{{ form.departure_city.value }}"/>
                                    <input type="hidden" name="city_to" value="{{ form.arrival_city.value }}"/>
                                    <input type="hidden" name="datetime_beg" value="{{ flight.departure_at }}"/>
                                    <input type="hidden" name="duration" value="{{ flight.duration }}"/>
                                    <input type="hidden" name="datetime_end" value="{{ flight.return_at }}"/>
                                    <input type="hidden" name="price" value="{{ flight.price }}"/>
                                    <input type="hidden" name="airline" value="{{ flight.airline }}"/>
                                    <div class="col text-center">
                                        <button type="submit" class="btn btn-success">
                                            Добавить в путешествие
                                        </button>
                                    </div>
                                </form>
                            </ul>
                            </p>
                        </div>

                    {% endfor %}
                </div>
            {% endif %}
            {% if data.success and not data.data %}
                <p class="warning">Рейсы не найдены. Попробуйте изменить условия поиска.
                </p>
            {% endif %}
            {% if data.error %}
                <p class="warning">Ошибка поиска. Попробуйте позже.
                </p>
            {% endif %}
            {#            <ul>#}
            {#                <a href="{% url 'waysearch:index' %}">#}
            {#                    {% trans "На главную страницу" %}#}
            {#                </a>#}
            {#            </ul>#}
        </div>
    </div>
    <script>
        $(function () {
            let availableTags = [
                {% for code in data.iata %}
                    {% if code.city_name == 'Москва' %}
                        "{{ code.city_name }} ({{ code.name }})",
                    {% else %}
                        "{{ code.city_name }}",
                    {% endif %}
                {% endfor %}
            ];
            $(".city-auto").autocomplete({
                source: availableTags
            });
        });
    </script>
{% endblock %}

travelru/waysearch/templates/search_train.html
{% extends "base.html" %}

{% load i18n %}


{% block page_title %}
    Search
{% endblock %}


{% block main_container %}

    <div class="container-md py-2">
    <h3>Поиск Ж/Д билетов</h3>
    <ul>
        <a href="{% url 'waysearch:index' %}">На главную</a>
    </ul>
    </div>
{% endblock %}