travelru/search_hotels/urls.py
# pylint: disable=invalid-name

from django.urls import path

from search_hotels.views import search_hotels, add_hotel_to_travel

app_name = "search_hotels"

urlpatterns = [
    path("", search_hotels, name="search_hotels"),
    path("add/", add_hotel_to_travel, name="add_hotel_to_travel"),
#    path("my-travel/", my_travel, name="my_travel"),

]

travelru/travelru/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("my-travel/", include("my_travel.urls", namespace="my_travel")),
    path("", include("waysearch.urls", namespace="waysearch")),
    path('search_hotels/', include('search_hotels.urls', namespace='search_hotels')),  # noqa: E501

]

travelru/waysearch/urls.py
from django.urls import path
from waysearch.views import search_avia_page, search_train_page, index, add_avia_to_travel

app_name = "waysearch"  # pylint: disable=invalid-name

urlpatterns = [
    path("", index, name="index"),
    path("search_avia/", search_avia_page, name="search_avia"),
    path("search_avia/add/", add_avia_to_travel, name="add_avia_to_travel"),
    path("search_train/", search_train_page, name="search_train"),

]

travelru/search_hotels/models.py
"""
models
"""

# from django.db import models

# Create your models here.

travelru/search_hotels/forms.py
"""
forms
"""
# flake8: noqa
from django import forms


class SearchHotelsForm(forms.Form):
    """
    searchhotelsform
    """

    city = forms.CharField(label='Город', widget=forms.TextInput(
        attrs={'class': 'form-control',
               'placeholder': 'Введите город',
               'id': 'city'})
               )
    check_in = forms.DateField(label='Дата заезда',
                               widget=forms.DateInput(
                                attrs={
                                    'class': 'form-control',
                                    'type': 'date',
                                    'id': 'check_in',
                                    'onkeydown': 'return false'}),
                               )
    check_out = forms.DateField(label='Дата выезда',
                                widget=forms.DateInput(
                                    attrs={
                                        'class': 'form-control',
                                        'type': 'date',
                                        'id': 'check_out',
                                        'onkeydown': 'return false'})
                                )
    amount_guests = forms.IntegerField(label='Гости', min_value=1, max_value=30,
                                       widget=forms.NumberInput(attrs={'class': 'form-control'}),
                                       initial=2)  # noqa: E501

travelru/search_hotels/views.py
"""
views
"""
# pylint: skip-file
# flake8: noqa

from datetime import datetime
from typing import List, Any, Optional

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate
import requests
from search_hotels.configuration_cities_hotels import cities_with_id
from search_hotels.forms import SearchHotelsForm
from travelru.settings import TOKEN_AVIASALES
from my_travel.models import Item, Hotel


def get_id_from_city(city_name: str, cities_list: list):  # pylint: disable=E1136 # noqa: E501
    """
    get_id_from_city
    """
    for city in cities_list:
        if city['name'].lower() == city_name.lower():
            return city['id']
    return 'error'


"""
запрос с формой
"""


def int_or_none(val: Any) -> Optional[int]:
    return int(val) if val is not None else None


def get_hotels_data(check_in: datetime.date, check_out: datetime.date, city_id: str, amount_guests: int) -> List[dict]:
    url = 'http://yasen.hotellook.com/tp/public/widget_location_dump.json'
    params = {'check_in': check_in,
              'check_out': check_out,
              'currency': 'rub',
              'language': 'ru',
              # 'limit': '5',
              'type': 'popularity',
              'id': city_id,
              'token': TOKEN_AVIASALES}

    dirty_hotel_data = requests.get(url, params=params).json()
    # print(dirty_hotel_data)
    # print('url', url, params)
    hotel_data = []
    for value_hotel_data in dirty_hotel_data['popularity']:
        try:
            search_params = value_hotel_data.get('last_price_info')['search_params']
            price_per_night = round(value_hotel_data.get('last_price_info')['price_pn'])
            nights_amount = int(value_hotel_data.get('last_price_info')['nights'])
            one_hotel_info = dict(
                name=value_hotel_data.get('name'),
                stars=int_or_none(value_hotel_data.get('stars')),
                hotel_type=value_hotel_data.get('hotel_type'),
                price=price_per_night,
                nights=nights_amount,
                total_cost=price_per_night * nights_amount * amount_guests,
                check_in=datetime.strptime(search_params['checkIn'], '%Y-%m-%d').date(),
                check_out=datetime.strptime(search_params['checkOut'], '%Y-%m-%d').date(),
                amount_guests=amount_guests
            )
            hotel_data.append(one_hotel_info)

        except TypeError:
            pass
    # print(hotel_data)
    return hotel_data


def get_sorted_hotels(hotels_list: List[dict]) -> List[dict]:
    sorted_hotels_list = sorted(hotels_list, key=lambda k: k['price'])
    return sorted_hotels_list


def search_hotels(request):
    """
    search_hotels
    """
    print('search_hotels')

    # today_date = datetime.today().strftime("%Y-%m-%d")
    cities = cities_with_id
    if request.method == "POST":
        # print(request.POST)
        search_form = SearchHotelsForm(request.POST)

        if search_form.is_valid():
            city = search_form.cleaned_data['city']
            check_in = search_form.cleaned_data['check_in']
            check_out = search_form.cleaned_data['check_out']
            amount_guests = int(search_form.cleaned_data['amount_guests'])
            if check_out < check_in:
                search_form.add_error('check_out', 'Дата выезда не может быть раньше даты заезда!')
                return render(request, "search_hotels.html", {'form': search_form})
            elif check_out == check_in:
                search_form.add_error('check_out', 'Дата выезда не может совпадать с датой заезда!')
                return render(request, "search_hotels.html", {'form': search_form})
            city_id = get_id_from_city(city, cities_with_id)
            if city_id == 'error':
                search_form.add_error('city', 'Такого города нет в базе')
                return render(request, "search_hotels.html", {'form': search_form})
            hotel_data = get_hotels_data(check_in, check_out, city_id, amount_guests)
            sorted_hotel_data = get_sorted_hotels(hotel_data)
            print('hotel data', hotel_data)
            # print('hotel data', sorted_hotel_data)
            return render(request, "search_hotels.html", {'form': search_form,
                                                          # 'today_date': today_date,
                                                          'after_request': True,
                                                          'hotel_data': sorted_hotel_data,
                                                          'cities': cities})  # pylint: disable=line-too-long
        else:  # pylint: disable=C0305
            return render(request, "search_hotels.html", {'form': search_form})
    else:
        search_form = SearchHotelsForm()

        return render(request, "search_hotels.html", {'form': search_form,
                                                      # 'today_date': today_date,
                                                      'cities': cities})


def add_hotel_to_travel(request):
    print(request.POST)
    name = request.POST['name']
    # price = float(request.POST['price'].replace(",", "."))
    price = int(request.POST['price'])
    hotel_city = request.POST['city']
    hotel_nights = request.POST['nights']
    total_cost = request.POST['total_cost']
    date_beg = datetime.strptime(request.POST['check_in'], "%d-%m-%Y").date()
    date_end = datetime.strptime(request.POST['check_out'], "%d-%m-%Y").date()
    time_beg = datetime.strptime("13:00", "%H:%M").time()
    time_end = datetime.strptime("11:00", "%H:%M").time()

    if not request.user.is_authenticated:
        print('AnonimousUser detected!')
        user = authenticate(username='guest', password='fdsa4321')
    else:
        user = request.user

    hotel = Hotel.objects.create(name=name,
                                 item_type="HOTEL",
                                 price=price,
                                 user=user,
                                 hotel_city=hotel_city,
                                 nights=hotel_nights,
                                 total_cost=total_cost,
                                 # date_beg=date_beg, date_end=date_end,
                                 # time_beg=time_beg, time_end=time_end
                                 )
    # item = Item.objects.create(name=name, item_type="HOTEL", price=price, user=user,
    #                            hotel_city=hotel_city,
    #                            date_beg=date_beg, date_end=date_end,
    #                            time_beg=time_beg, time_end=time_end)
    #    add_hotel_item_to_models(hotel_data)
    return HttpResponseRedirect('/my-travel')

travelru/search_hotels/templates/search_hotels.html
{% extends 'base.html' %}
{% load i18n %}
{% load calculation_tag %}

{% block page_title %}
    Поиск отелей
{% endblock %}

{% block js %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>

{% endblock %}

{% block main_container %}
    <div class="container-md py-2">
        <div><h3 class="text-center" style="
                 margin-bottom: 40px;">Поиск отелей на Create-travel.ru</h3></div>
        <div class="forms-resolver">
            <form method="post" class="row gy-2 gx-3 align-items-center mb-3">
                {% csrf_token %}
                <div class="row row-cols-5">
                    <div class="col">{{ form.city.label }}</div>
                    <div class="col">{{ form.check_in.label }}</div>
                    <div class="col">{{ form.check_out.label }}</div>
                    <div class="col">{{ form.amount_guests.label }}</div>
                    <div class="col"></div>
                    <div class="col">{{ form.city|default:'' }}</div>
                    <div class="col">{{ form.check_in }}</div>
                    <div class="col">{{ form.check_out }}</div>
                    <div class="col">{{ form.amount_guests }}</div>
                    <div class="col">
                        <button type="submit" class="btn btn-primary">{% trans "Найти отели" %}</button>
                    </div>
                </div>
            </form>
            {% for error, descriptions in form.errors.items %}
                {% for description in descriptions %}
                    <p class="text-danger">{{ description }}</p>
                {% endfor %}
            {% endfor %}
        </div>
        {% if after_request and not hotel_data %}
            <p class="warning">Отели не найдены. Попробуйте изменить условия поиска.
            </p>
        {% endif %}



        <div class="container-md py-2">
            {% for hotel in hotel_data %}
                <div class="p-3 mb-4 bg-light rounded-3">
                    <div class="container-md py-2" style="padding-top: 5px; margin-left: 20px;">
                        <h5>{{ hotel.name }}</h5>
                        <p>
                            {% for i in hotel.stars|times %}
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-star-fill" viewBox="0 0 16 16">
                                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                                </svg>

                            {% endfor %}
                        </p>
                        <p>
                            {% for type in  hotel.hotel_type %}
                                <a href="#"> {{ type }}</a>
                            {% endfor %}
                        <ul class="list-inline">
                            <li class="list-inline-item">{{ hotel.check_in|date:"d E Y" }}
                                - {{ hotel.check_out|date:"d E Y" }}</li>
                        </ul>
                        <ul class="list-inline">
                            <li class="list-inline-item">Цена за сутки: {{ hotel.price }} ₽</li>
                            <li class="list-inline-item">Количество ночей: {{ hotel.nights }}</li>
                            <li class="list-inline-item ">
{#                                <strong>Стоимость: {% total_cost hotel.price hotel.nights hotel.amount_guests %}#}
{#                                    ₽</strong>#}
                                <strong>Стоимость: {{ hotel.total_cost }}
                                    ₽</strong>
                            </li>
                            <ul class="list-inline">
                                <form method="post" action="{% url 'search_hotels:add_hotel_to_travel' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="city" value="{{ form.city.value }}"/>
                                    <input type="hidden" name="name" value="{{ hotel.name }}"/>
                                    <input type="hidden" name="check_in" value="{{ hotel.check_in|date:"d-m-Y" }}"/>
                                    <input type="hidden" name="check_out" value="{{ hotel.check_out|date:"d-m-Y" }}"/>
                                    <input type="hidden" name="nights" value="{{ hotel.nights }}"/>
                                    <input type="hidden" name="price" value="{{ hotel.price }}"/>
                                    <input type="hidden" name="total_cost" value="{{ hotel.total_cost }}"/>
                                    <button type="submit" class="btn btn-success" style="margin-top: 20px;">
                                        Добавить в путешествие
                                    </button>
                                </form>
                            </ul>
                        </ul>
                    </div>
                </div>
            {% endfor %}
            {#            <ul>#}
            {#                <a href="{% url 'waysearch:index' %}">#}
            {#                    {% trans "На главную страницу" %}#}
            {#                </a>#}
            {#            </ul>#}
        </div>

        <script type="text/javascript">
            var today = new Date();
            var dd = String(today.getDate()).padStart(2, '0');
            var mm = String(today.getMonth() + 1).padStart(2, '0');
            var yyyy = today.getFullYear();

            today = yyyy + '-' + mm + '-' + dd;
            $('#check_in').attr('min', today);
            $('#check_out').attr('min', today);
        </script>

        <script>
            $(function () {
                var availableTags = [
                    {% for city in cities %}
                        "{{ city.name }}",
                    {% endfor %}
                ];
                $("#city").autocomplete({
                    source: availableTags
                });
            });
        </script>
    </div>
{% endblock %}